angular.module('app')
    .factory('Badges', function () {
        return ["img/badges/Android/installer-le-sdk.png",
                "img/badges/Angular/angular-data-binding.png",
                "img/badges/Autres/enrichir-profil-user-firebase.png",
                "img/badges/Bootstrap/bootstrap.png",
                "img/badges/BDD/a-la-decouverte-des-bdd.png",
                "img/badges/CSS/integrer-maquette-html-css.png",
                "img/badges/Git/comprendre-git.png",
                "img/badges/GitHub/hello-github.png",
                "img/badges/HTML/html5-css3.png",
                "img/badges/Javascript/decouverte-nodejs.png",
                //Android
                "img/badges/Android/adapter.png",
                "img/badges/Android/creer-app-simple.png",
                "img/badges/Android/les-objets-parcelable.png",
                "img/badges/Android/plusieurs-activities.png",
                "img/badges/Android/utiliser-le-datapickerdialog.png",
                //Autres
                "img/badges/Autres/gerer-connexion-firebase.png",
                "img/badges/Autres/restful.png",
                "img/badges/Autres/se-connecter-a-bdd-firebase.png",
                "img/badges/Autres/traduire-une-app.png",
                "img/badges/Autres/utiliser-geolocalisation.png",
                //BDD
                "img/badges/BDD/discuter-en-sql.png",
                "img/badges/BDD/interagir-avec-bdd-sql-2.png",
                "img/badges/BDD/interagir-avec-bdd-sql.png",
                //Git
                "img/badges/Git/git-workflow.png",
                //Javascript
                "img/badges/Javascript/dynamiser-le-dom.png",
                "img/badges/Javascript/httpRequest.png",
                "img/badges/Javascript/Javascripting.png",
                "img/badges/Javascript/jQuery.png",
                "img/badges/Javascript/serveur-http.png",
                //PHP
                "img/badges/PHP/dans-la-peau-dun-cornac.png",
                "img/badges/PHP/installation-outils-php.png",
                "img/badges/PHP/installation-phpstorm.png",
                "img/badges/PHP/installation-xdebug.png",
                "img/badges/PHP/laisse-pas-tainer-ton-file.png",
                "img/badges/PHP/php-oriente-objet.png",
                "img/badges/PHP/retour-vers-le-futur.png",
                //ruby
                "img/badges/Ruby/bundler-gemfile.png",
                "img/badges/Ruby/ma-premiere-gem.png",
                "img/badges/Ruby/ruby-debuggeur.png",
                "img/badges/Ruby/ruby-new.png",
                "img/badges/Ruby/sinatra.png",
                //Symfony
                "img/badges/Symfony/generer-le-crud.png",
                "img/badges/Symfony/relations-entre-entites.png",
                "img/badges/Symfony/symfony-creation-dun-projet.png",
                "img/badges/Symfony/symfony-linterface-admin.png",
                //Unix
                "img/badges/Unix/gist-in-the-cli.png",
                "img/badges/Unix/linux-tips.png",
                "img/badges/Unix/maitriser-unix.png",
                "img/badges/Unix/unix-au-pays-des-merveilles.png",
                //WCS
                "img/badges/WCS/mission-candidats.png",
                //Wild
                "img/badges/Wild/apprendre-a-apprendre.png",
                "img/badges/Wild/cv-linkedin.png",
                "img/badges/Wild/markdown.png",
                "img/badges/Wild/pseudo-code.png"
              ];
    });
